- id: sound_alarm_from_notification
  alias: Sound alarm from notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  action:
  - service: homeassistant.turn_on
    entity_id: script.sonos_alarm
  - service: light.turn_on
    data:
      entity_id: group.all_lights
- id: alarm_off_from_notification
  alias: Turn alarm off from notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
  - service: media_player.turn_off
- id: sensors_changed_when_nobody_home
  alias: Sensors tripped when nobody is home
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_boolean.cottage_guest_mode
    state: 'off'
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
    for: 00:05:00
  trigger:
  - platform: state
    entity_id:
    - group.smoke_sensors
    - group.motion_sensors
    - group.door_sensors
    from: 'off'
    to: 'on'
  action:
  - delay: 00:05:00
  - condition: state
    entity_id: group.family
    state: not_home
  - service: light.turn_on
    data:
      entity_id: group.all_lights
  - service: notify.mobile_app_lars_iphone
    data_template:
      title: LARM!
      message: The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state
        }} while no one is home - {{ as_timestamp(now()) | timestamp_custom('%Y-%m-%d
        %H:%M:%S', True) }}
      data:
        push:
          badge: 666
          category: alarm
  - service: homeassistant.turn_on
    entity_id: script.sonos_alarm
- id: door_open
  alias: Door open if night or away
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: group.door_sensors
    state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.cottage_status
    to: Night
  - platform: state
    entity_id: input_select.cottage_status
    to: Away
  action:
  - service: notify.mobile_app_lars_iphone
    data_template:
      title: Dörr öppen!
      message: '{{ trigger.to_state.name }} är öppen!'
      data:
        push:
          badge: 100
          category: notis
- id: storage_cold
  alias: Kallt i förråd
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.smoke_sensor_storage_temperature
    below: 10
  action:
  - service: notify.mobile_app_lars_iphone
    data:
      title: Larm
      message: Det är under 10°C i förrådet!
      data:
        push:
          badge: 500
          category: notis
- id: arm_cottage
  alias: Arm the house
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_boolean.cottage_guest_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.cottage_status
      state: Home
      for: 00:10:00
    - condition: state
      entity_id: input_select.cottage_status
      state: Standby
      for: 00:10:00
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for: 00:05:00
  action:
    service: homeassistant.turn_on
    entity_id: script.cottage_away
- id: disarm_cottage_from_away
  alias: Disarm house from Away
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  trigger:
  - platform: state
    entity_id:
    - person.lars
    - person.emelie
    - group.family
    to: home
  - platform: state
    entity_id: input_boolean.cottage_guest_mode
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.cottage_standby
- id: disarm_cottage_from_night
  alias: Disarm house from Night
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_select.cottage_status
    state: Night
  trigger:
  - platform: state
    entity_id:
    - person.lars
    - person.emelie
    - group.family
    to: home
  - platform: state
    entity_id: input_boolean.cottage_guest_mode
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.cottage_standby
- id: cottage_home
  alias: House home mode
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 07:30:00
      before: '22:30:00'
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: input_select.cottage_status
      state: Standby
      for: 00:20:00
    - condition: or
      conditions:
      - condition: state
        entity_id: group.family
        state: home
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /10
  action:
  - service: homeassistant.turn_on
    entity_id: script.cottage_home
- id: cottage_standby_morning
  alias: House morning Standby
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time
    at: 05:00:00
  action:
  - service: homeassistant.turn_on
    entity_id: script.cottage_standby
- id: cottage_standby_at_evening
  alias: House evening Standby
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - service: homeassistant.turn_on
    entity_id: script.cottage_standby
- id: cottage_to_night
  alias: House Night mode
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: time
      after: 00:15:00
      before: 05:00:00
    - condition: state
      entity_id: input_select.cottage_status
      state: Standby
      for: 00:50:00
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time_pattern
    minutes: /10
  action:
  - service: homeassistant.turn_on
    entity_id: script.cottage_night
- id: turn_off_lights_when_away
  alias: Lights off when Away
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  trigger:
  - platform: time
    at: 00:16:00
  action:
  - service: light.turn_off
    entity_id:
    - group.bedroom_lights
    - group.window_lights
- id: lights_on_pre_kids_bedtime
  alias: Lights on pre kids bedtime
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: time
    after: '15:00:00'
    before: '19:00:00'
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.0
  action:
  - service: light.turn_on
    data:
      entity_id: group.all_lights
      brightness: 120
      transition: 180
- id: lights_on_evening
  alias: Lights on evening
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: time
      after: '19:00:00'
      before: '20:30:00'
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.0
  action:
  - service: light.turn_on
    data:
      brightness: 20
      entity_id: group.window_lights
- id: morning_lights_weekday
  alias: Morning lights weekday
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: light.window_lights_downstairs
      state: 'off'
    - condition: time
      after: 05:30:00
      before: 09:30:00
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_262a7502_1_1280
    to: 'on'
  action:
  - service: light.turn_on
    data:
      brightness: 255
      entity_id: group.window_lights
- id: lights_on_up_night_motion
  alias: Lights upstairs night motion
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: light.window_lights_upstairs
      state: 'off'
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_262a7502_1_1280
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.window_lights_upstairs
  - delay: 00:04:00
  - service: light.turn_off
    entity_id: light.window_lights_upstairs
- id: lights_on_down_night_motion
  alias: Lights downstairs night motion
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: light.window_lights_downstairs
      state: 'off'
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_fbc65302_1_1280
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.window_lights_downstairs
  - delay: 00:04:00
  - service: light.turn_off
    entity_id: light.window_lights_downstairs
- id: wake_up_lights_weekday
  alias: Wake up light weekdays
  trigger:
  - at: 05:50
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: group.family
      state: home
  action:
  - data:
      brightness: 10
      entity_id: group.bedroom_lights
      transition: 18000
    service: light.turn_on
  initial_state: 'on'
- id: remote_ingrid_on_off
  alias: Ingrid remote on/off
  trigger:
  - device_id: 42d25b9aa10447179486ffe1f37ee1cd
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  action:
  - device_id: a83fe854367e4320a30d5d357a5d8ea2
    domain: light
    entity_id: light.ingrid_bedroom_color
    type: toggle
  initial_state: 'on'
- id: remote_bed_time
  alias: Remote all lights on/off
  trigger:
  - device_id: 42d25b9aa10447179486ffe1f37ee1cd
    domain: zha
    platform: device
    subtype: left
    type: remote_button_short_press
  action:
  - device_id: a83fe854367e4320a30d5d357a5d8ea2
    domain: light
    entity_id: light.ingrid_bedroom_color
    type: toggle
  initial_state: 'on'
- id: remote_on_master_bedroom
  alias: Remote master bedroom on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_of_sweden_tradfri_on_off_switch_fed2b62d_1_1
      event: 1002
  action:
    service: light.toggle
    entity_id: light.master_bedroom_window
- id: car_heater_start
  alias: Engine heater activate
  trigger:
  - platform: template
    value_template: '{{ states.sensor.heater_activationtime.state == states(''sensor.time'')
      }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.workdays_only
        state: 'off'
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.workdays_only
          state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_fefd82b0_1
- id: car_heater_shut_down
  alias: Engine heater deactivate
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.heater_departuretime.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  action:
  - delay:
      minutes: '{{ states(''input_number.heater_delay'') | int }}'
  - service: switch.turn_off
    entity_id: switch.ikea_of_sweden_tradfri_control_outlet_fefd82b0_1
- id: ifttt_automation
  alias: IFTTT automation
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
  - service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
- id: extra_vvc_weekend
  alias: VVC on weekend earlier
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'off'
  - condition: state
    entity_id: group.family
    state: home
  trigger:
  - platform: time
    at: 07:00:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.vvc
- id: high_electric_price
  alias: Högt elpris
  condition:
  - condition: time
    after: 08:00:00
    before: '21:00:00'
  trigger:
  - platform: numeric_state
    entity_id: sensor.nibe_31372_10069
    above: 80
  action:
  - service: notify.mobile_app_lars_iphone
    data:
      title: Elpris!
      message: Spot-pris över 80 öre!
      data:
        push:
          category: notis
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.kok_vardagsrum
      volume: 0.45
      delay: 00:00:15
      message: Hej, tänk på att det just nu är högt elpris. Det ligger just nu på
        {{ states.sensor.nibe_31372_10069.state }} öre per kWh!
- id: low_electric_price
  alias: Lågt elpris
  condition:
  - condition: time
    after: 08:00:00
    before: '21:00:00'
  trigger:
  - platform: numeric_state
    entity_id: sensor.nibe_31372_10069
    below: 20
  action:
  - service: notify.mobile_app_lars_iphone
    data:
      title: Elpris!
      message: Spot-pris under 20 öre!
      data:
        push:
          category: notis
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.kok_vardagsrum
      volume: 0.45
      delay: 00:00:15
      message: Hej, just nu är det lågt elpris, {{ states.sensor.nibe_31372_10069.state
        }} öre per kWh närmaste timen
- id: update_of_hass
  alias: Notification Update Hass Available
  condition:
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.mobile_app_lars_iphone
    data:
      title: Uppdatering!
      message: Ny version av Home Assistant tillgänglig!
      data:
        push:
          badge: 10
          category: notis
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.kok_vardagsrum
      volume: 0.45
      delay: 00:00:15
      message: Hej, det finns en ny uppdatering av Home Assistant
- id: fire_alarm
  alias: Smoke detectors tripped
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - group.smoke_sensors
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    data:
      brightness: 255
      color_temp: 454
    entity_id: group.all_lights
  - service: notify.mobile_app_lars_iphone
    data_template:
      title: BRANDLARM!!
      message: “En brandvarnare har löst ut!”
      data:
        push:
          badge: 999
          category: alarm
  - service: homeassistant.turn_on
    entity_id: script.sonos_fire_alarm
- id: cleaning_robot_running
  alias: Neato running take down sensors
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: vacuum.stadstina
    to: cleaning
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.cottage_guest_mode
- id: cleaning_robot_docked
  alias: Neato finished
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  trigger:
  - platform: state
    entity_id: vacuum.stadstina
    to: docked
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.cottage_guest_mode
- id: sonos_enable_speech_enhance_and_night_sound
  alias: Sonos Enable speech enhance and night sound
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.allrum
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '20:30:00'
    before: 01:00:00
  action:
  - service: sonos.set_option
    data:
      entity_id: media_player.sallskapsrum
      night_sound: true
  - service: sonos.set_option
    data:
      entity_id: media_player.sallskapsrum
      speech_enhance: true
- id: sonos_disable_speech_enhance_and_night_sound
  alias: Sonos Disable speech enhance and night sound
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.allrum
    to: 'off'
  condition:
  - condition: time
    after: '20:30:00'
    before: 07:00:00
  action:
  - service: sonos.set_option
    data:
      entity_id: media_player.sallskapsrum
      night_sound: false
  - service: sonos.set_option
    data:
      entity_id: media_player.sallskapsrum
      speech_enhance: false
- id: '1572374206212'
  alias: Kerstins fjärr on/off
  description: ''
  trigger:
  - device_id: 1219587387e14c04a57b426377dbabe9
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 36a61a6f70d245f8838ce46cf2b2d2aa
    domain: light
    entity_id: light.kerstin_bedroom_color
    type: toggle
- id: '1573683417414'
  alias: 'Ingrid remote night mode '
  description: ''
  trigger:
  - device_id: 42d25b9aa10447179486ffe1f37ee1cd
    domain: zha
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  condition: []
  action:
  - device_id: a711302a44c14ef2b50af13327c8d54c
    domain: light
    entity_id: light.ingrid_bedroom_window
    type: turn_off
  - device_id: f03f6625c52a4025a1eed5220bfa277c
    domain: light
    entity_id: light.ingrid_bedroom_bed_light
    type: turn_off
  - device_id: aef6fc73e81442519b874f6a6353d193
    domain: light
    entity_id: light.innr_rb_145_01c3e036_1
    type: turn_off
