- id: sound_alarm_from_notification
  alias: Sound alarm from notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  action:
  - service: homeassistant.turn_on
    entity_id: script.sonos_alarm
  - service: light.turn_on
    data:
      entity_id: group.all_lights
- id: alarm_off_from_notification
  alias: Turn alarm off from notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
  - service: media_player.turn_off
- id: sensors_changed_when_nobody_home
  alias: Sensors tripped when nobody is home
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_boolean.cottage_guest_mode
    state: 'off'
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
    for: 00:05:00
  trigger:
  - platform: state
    entity_id:
    - group.smoke_sensors
    - group.motion_sensors
    - group.door_sensors
    from: 'off'
    to: 'on'
  action:
  - delay: 00:05:00
  - condition: state
    entity_id: group.family
    state: not_home
  - service: light.turn_on
    data:
      entity_id: group.all_lights
  - service: notify.all_devices
    data:
      title: LARM!
      message: The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state}}
        while no one is home - {{ as_timestamp(now()) | timestamp_custom('%Y-%m-%d%H:%M:%S',
        True) }}
      data:
        push:
          badge: 666
          category: alarm
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: script.sonos_alarm
  - service: script.light_alarm
- id: door_open
  alias: Door open if night or away
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: group.door_sensors
    state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.cottage_status
    to: Night
  - platform: state
    entity_id: input_select.cottage_status
    to: Away
  action:
  - service: notify.all_devices
    data:
      title: Dörr öppen!
      message: '{{ trigger.to_state.name }} är öppen!'
      data:
        push:
          badge: 100
          category: notis
- id: arm_cottage
  alias: Arm the house
  trigger:
  - entity_id: group.family
    for: 00:05:00
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_boolean.cottage_guest_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.cottage_status
      for: 00:10:00
      state: Home
    - condition: state
      entity_id: input_select.cottage_status
      for: 00:10:00
      state: Standby
  action:
  - service: script.cottage_away
  initial_state: 'on'
- id: disarm_cottage_from_away
  alias: Disarm house from Away
  trigger:
  - entity_id:
    - person.lars
    - person.emelie
    - person.guest
    - person.gast
    platform: state
    to: home
  - entity_id: input_boolean.cottage_guest_mode
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  action:
  - service: script.cottage_standby
  initial_state: 'on'
- id: disarm_cottage_from_night
  alias: Disarm house from Night
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - condition: state
    entity_id: input_select.cottage_status
    state: Night
  trigger:
  - platform: state
    entity_id:
    - person.lars
    - person.emelie
    - person.guest
    - person.gast
    to: home
  - platform: state
    entity_id: input_boolean.cottage_guest_mode
    to: 'on'
  action:
  - service: script.cottage_standby
- id: cottage_home
  alias: House home mode
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 07:30:00
      before: '22:30:00'
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: input_select.cottage_status
      state: Standby
      for: 00:20:00
    - condition: or
      conditions:
      - condition: state
        entity_id: group.family
        state: home
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
  trigger:
  - platform: time_pattern
    minutes: /10
  action:
  - service: script.cottage_home
- id: cottage_standby_morning
  alias: House morning Standby
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time
    at: 05:00:00
  action:
  - service: script.cottage_standby
- id: cottage_standby_at_evening
  alias: House evening Standby
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - service: script.cottage_standby
- id: cottage_to_night
  alias: House Night mode
  initial_state: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: time
      after: 00:15:00
      before: 05:00:00
    - condition: state
      entity_id: input_select.cottage_status
      state: Standby
      for: 00:50:00
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.cottage_guest_mode
        state: 'on'
      - condition: state
        entity_id: group.family
        state: home
  trigger:
  - platform: time_pattern
    minutes: /10
  action:
  - service: script.cottage_night
- id: turn_off_lights_when_away
  alias: lights off when away
  trigger:
  - at: 00:16:00
    platform: time
  condition:
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  action:
  - data:
      entity_id:
      - group.bedroom_lights
      - group.ingrid_lights
      - group.kerstin_lights
    service: light.turn_off
  initial_state: 'on'
- id: lights_on_pre_kids_bedtime
  alias: lights on if time is before kids bedtime
  trigger:
  - below: '1'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  - after: '12:00:00'
    before: '18:00:00'
    condition: time
  action:
  - data:
      brightness: 120
      entity_id:
      - group.window_lights
      - group.window_lights_bedroom
      - group.outdoor_lights
      transition: 180
    service: light.turn_on
  initial_state: 'on'
- id: lights_on_evening
  alias: lights on evening
  trigger:
  - below: '1'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - after: '18:00:00'
      before: '20:30:00'
      condition: time
  action:
  - data:
      brightness: 100
      entity_id:
      - group.window_lights_excl_kids
      - group.outdoor_lights
      - light.storage_window_light
    service: light.turn_on
  initial_state: 'on'
- id: morning_lights_weekday
  alias: lights on morning weekday
  trigger:
  - entity_id: binary_sensor.family_room_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: group.family
      state: home
    - condition: state
      entity_id: group.window_lights
      state: 'off'
    - after: 05:30:00
      before: 09:30:00
      condition: time
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
  action:
  - data:
      brightness: 255
      entity_id: group.window_lights
    service: light.turn_on
  initial_state: 'on'
- id: lights_on_up_night_motion
  alias: lights on at night upstairs when motion detected
  trigger:
  - entity_id: binary_sensor.family_room_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: light.window_lights_upstairs
    state: 'off'
  action:
  - entity_id: light.window_lights_upstairs
    service: light.turn_on
  - delay: 00:20:00
  - entity_id: light.window_lights_upstairs
    service: light.turn_off
  initial_state: 'on'
- id: lights_on_down_night_motion
  alias: lights on at night downstairs when motion detected
  trigger:
  - entity_id: binary_sensor.hall_motion_sensor
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_motion_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: '22:00:00'
      condition: time
    - condition: state
      entity_id: light.window_lights_downstairs
      state: 'off'
  action:
  - entity_id: light.window_lights_downstairs
    service: light.turn_on
  - delay: 00:10:00
  - entity_id: light.window_lights_downstairs
    service: light.turn_off
  initial_state: 'on'
- id: wake_up_lights_weekday
  alias: light wake up weekdays
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: group.family
      state: home
  action:
  - data:
      brightness: 10
      entity_id: group.bedroom_lights
      transition: 1800
    service: light.turn_on
  initial_state: 'on'
- id: car_heater_start
  alias: Engine heater activate
  trigger:
  - platform: template
    value_template: '{{ states.sensor.heater_activationtime.state == states(''sensor.time'')
      }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.workdays_only
        state: 'off'
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.workdays_only
          state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.carport_car_heater
- id: car_heater_shut_down
  alias: Engine heater deactivate
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.heater_departuretime.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  action:
  - delay:
      minutes: '{{ states(''input_number.heater_delay'') | int }}'
  - service: switch.turn_off
    entity_id: switch.carport_car_heater
- id: ifttt_automation
  alias: IFTTT automation
  trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
  - service_template: '{{ trigger.event.data.service }}'
    data:
      entity_id: '{{ trigger.event.data.entity_id }}'
- id: extra_vvc_weekend
  alias: VVC on weekend earlier
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'off'
  - condition: state
    entity_id: group.family
    state: home
  trigger:
  - platform: time
    at: 06:30:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.storage_hwc
- id: high_electric_price
  alias: Högt elpris
  condition:
  - condition: time
    after: 08:00:00
    before: '21:00:00'
  trigger:
  - platform: numeric_state
    entity_id: sensor.nibe_31372_10069
    above: 80
  action:
  - service: notify.all_devices
    data:
      title: Elpris!
      message: Spot-pris över 80 öre!
      data:
        push:
          category: notis
  - service: script.sonos_say
    data:
      sonos_entity: media_player.allrum_2
      volume: 0.45
      delay: 00:00:15
      message: Hej, tänk på att det just nu är högt elpris. Det ligger just nu på
        {{ states.sensor.nibe_31372_10069.state }} öre per kWh!
- id: low_electric_price
  alias: Lågt elpris
  condition:
  - condition: time
    after: 08:00:00
    before: '21:00:00'
  trigger:
  - platform: numeric_state
    entity_id: sensor.nibe_31372_10069
    below: 20
  action:
  - service: notify.all_devices
    data:
      title: Elpris!
      message: Spot-pris under 20 öre!
      data:
        push:
          category: notis
  - service: script.sonos_say
    data:
      sonos_entity: media_player.allrum_2
      volume: 0.45
      delay: 00:00:15
      message: Hej, just nu är det lågt elpris, {{ states.sensor.nibe_31372_10069.state
        }} öre per kWh närmaste timen
- id: update_of_hass
  alias: Notification Update Hass Available
  condition:
  - condition: time
    after: 08:00:00
    before: '20:00:00'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.all_devices
    data:
      title: Uppdatering!
      message: Ny version av Home Assistant tillgänglig!
      data:
        push:
          category: notis
  - service: script.sonos_say
    data:
      sonos_entity: media_player.allrum_2
      volume: 0.45
      delay: 00:00:15
      message: Hej, det finns en ny uppdatering av Home Assistant
- id: fire_alarm
  alias: Smoke detectors tripped
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.smoke_sensors
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    data:
      brightness: 255
      color_temp: 454
    entity_id: group.all_lights
  - service: notify.all_devices
    data:
      title: BRANDLARM!!
      message: “En brandvarnare har löst ut!”
      data:
        push:
          badge: 999
          category: alarm
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: script.sonos_fire_alarm
- id: cleaning_robot_running
  alias: Neato running - Take down sensors
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.cottage_update
    state: 'on'
  trigger:
  - platform: state
    entity_id: vacuum.stadstina
    to: cleaning
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.cottage_guest_mode
- id: cleaning_robot_docked
  alias: Neato finished - Reset sensors
  trigger:
  - entity_id: vacuum.stadstina
    platform: state
    to: docked
  - entity_id: vacuum.stadstina
    platform: state
    to: idle
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.cottage_update
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.cottage_status
        for: 00:05:00
        state: Standby
      - condition: state
        entity_id: input_select.cottage_status
        for: 00:05:00
        state: Away
      - condition: state
        entity_id: input_select.cottage_status
        for: 00:05:00
        state: Home
  action:
  - entity_id: input_boolean.cottage_guest_mode
    service: input_boolean.turn_off
  initial_state: 'on'
- id: '1574533247410'
  alias: light stairs on when motion detected
  description: ''
  trigger:
  - entity_id: group.motion_sensors
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.hall_stairs_light
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - alias: ''
    data: {}
    entity_id: light.hall_stairs_light
    service: light.turn_on
- id: '1575229526062'
  alias: light increase outdoor lights when door opens
  description: ''
  trigger:
  - entity_id: group.door_sensors
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - scene: scene.outdoor_lights_max
- id: '1575235004195'
  alias: light stairs off when no motion detected
  description: ''
  trigger:
  - entity_id: group.motion_sensors
    for: 00:20:00
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.hall_stairs_light
    state: 'on'
  action:
  - alias: ''
    data: {}
    entity_id: light.hall_stairs_light
    service: light.turn_off
- id: '1576351177046'
  alias: light turn down outdoor lights when no door opened for one hour
  description: ''
  trigger:
  - entity_id: group.door_sensors
    for: 01:00:00
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - scene: scene.outdoor_lights_min
- id: '1576351426270'
  alias: light turn off outdoor lights when door closed during night
  description: ''
  trigger:
  - entity_id: group.door_sensors
    for: 03:00:00
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: binary_sensor.cottage_status_home
    state: 'on'
  action:
  - entity_id: group.outdoor_lights
    service: light.turn_off
- id: '1576406786036'
  alias: light turn off lights when sun is up
  description: ''
  trigger:
  - event: sunrise
    offset: 00:30:00
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id:
      - group.window_lights
      - group.window_lights_bedroom
      - group.outdoor_lights
      - light.storage_window_light
    service: light.turn_off
- id: '1576449718169'
  alias: 'ESP low battery '
  description: below 3.3V
  trigger:
  - below: '3.3'
    entity_id: sensor.weather_station_battery_voltage
    for: 01:00:00
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        push:
          category: notis
      message: Weather station is below 3.3V
      title: ESP low battery!
    service: notify.all_devices
- id: '1577656157721'
  alias: motion detected in carport when away
  description: ''
  trigger:
  - device_id: ff2e733bac234d60b1312f644e6eefdc
    domain: binary_sensor
    entity_id: binary_sensor.carport_motion_sensor
    platform: device
    type: motion
  condition:
  - condition: state
    entity_id: input_select.cottage_status
    state: Away
  action:
  - data:
      data:
        attachment:
          content-type: jpeg
        entity_id: camera.front
        push:
          category: camera
      message: Motion detected in carport
      title: Motion detected!
    service: notify.all_devices
