homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
      trusted_users:
        192.168.1.0/24:
          - 9b40eeeaefb24820940f02bc9ddbad86
  #Customize
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  #Packages
  packages: !include_dir_named packages

default_config:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
#  ip_ban_enabled: True
#  login_attempts_threshold: 5

updater:
  include_used_components: true

conversation:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'sv'
    time_memory: 21600

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  purge_interval: 5
  exclude:
    domains:
      # - script
      - weather
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_utc
      - sensor.last_boot
      # - group.door_sensors
      # - group.door_units
      # - group.motion_sensors
      # - group.motion_units

logbook:
  # exclude:
  #   domains:
  #     - device_tracker

logger:
  # default: info
  # logs:
  #   zigpy: debug
  #   bellows: debug
  #   zigpy_deconz: debug
  #   homeassistant.components.zha: debug

influxdb:
  host: 192.168.1.4
  port: 8086
  database: hass
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - light
      - switch
      - device_tracker
  exclude:
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_utc
      - sensor.last_boot
  tags:
    source: hass

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_key

zha:
  usb_path: /dev/ttyACM1
  database_path: /config/zigbee.db

neato:
  username: !secret neato_username
  password: !secret neato_password

nibe:
    systems:
        - system: '31372'
          units:
            - unit: 0
              categories: True
              statuses: True
          sensors:
            - 40067
            - 40014
            - 40013
            - 40004
            - 40083
            - 40081
            - 40079
            - 43005
            - 43416
            - 43439
            - 43347
            - 40015
            - 40016
            - 43420
            - 43424
            - 43136
            - 43009
            - 40008
            - 40012
            - 40033
          climates: False
          water_heaters: True

utility_meter:
  daily_energy:
    source: sensor.energy_meter_energy
    cycle: daily
  monthly_energy:
    source: sensor.energy_meter_energy
    cycle: monthly
  monthly_car_heater_energy:
    source: sensor.energy_car_heater
    cycle: monthly

camera:
  - platform: generic
    name: front
    still_image_url: !secret front_camera_still_url
    stream_source: !secret front_camera_stream_url
    username: !secret camera_username
    password: !secret camera_password
    authentication: digest
    verify_ssl: False
  # - platform: onvif
  #   name: carport
  #   host: !secret carport_camera_url
  #   port: !secret camera_port
  #   username: !secret camera_username
  #   password: !secret camera_password
  - platform: generic
    name: indoor
    still_image_url: !secret indoor_camera_still_url
    stream_source: !secret indoor_camera_stream_url
    username: !secret camera_username
    password: !secret camera_password
    authentication: digest
    verify_ssl: False

# ios:
#   push:
#     categories:
#       - name: Alarm
#         identifier: 'alarm'
#         actions:
#           - identifier: 'SOUND_ALARM'
#             title: "Starta larmet!!"
#             activationMode: 'background'
#             authenticationRequired: no
#             destructive: yes
#             behavior: 'default'
#           - identifier: 'SILENCE_ALARM'
#             title: "Tysta larmet"
#             activationMode: 'background'
#             authenticationRequired: no
#             destructive: no
#             behavior: 'default'
#       - name: Notification
#         identifier: 'notis'
#         actions:
#
# device_tracker:
#   - platform: unifi
#     host: 192.168.1.2
#     username: !secret unifi_username
#     password: !secret unifi_password
#     verify_ssl: false
#     ssid_filter:
#       - 'RunevadHome'
#       - 'RunevadGuest'
#     monitored_conditions:
#       - ip
#       - radio
#       - _is_guest_by_uap
#       - _last_seen_by_uap
#       - _uptime_by_uap
#     consider_home: 300
#     new_device_defaults:
#       track_new_devices: False
#       hide_if_away: False

owntracks:
  max_gps_accuracy: 300

group: !include_dir_merge_named group

automation: !include automations.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

switch: !include switch.yaml

light:
  - platform: switch
    name: "living_room_window_south"
    entity_id: switch.wall_plug_living_room_window_south
  - platform: switch
    name: "window_lights_downstairs"
    entity_id: switch.window_lights_downstairs
  - platform: switch
    name: "window_lights_upstairs"
    entity_id: switch.window_lights_upstairs
  - platform: switch
    name: "laundry_window_east"
    entity_id: switch.wall_plug_laundry_window_east

  - platform: group
    name: "Carport Lights"
    entities:
      - light.ikea_of_sweden_tradfri_bulb_e27_ws_clear_806lm_fe74d1de_1
      - light.ikea_of_sweden_tradfri_bulb_e27_ws_clear_806lm_fe9451d8_1
      - light.ikea_of_sweden_tradfri_bulb_e27_ws_clear_806lm_fe944cf0_1

binary_sensor:
  - platform: template
    sensors:
      cottage_status_home:
        value_template: "{{ states.group.family.state == 'home' }}"
        friendly_name: 'Home'
        device_class: occupancy
      cottage_update:
        value_template: "{{ states.input_boolean.cottage_update.state == 'off' }}"
        friendly_name: 'Auto'
        device_class: safety
      cottage_guest_mode:
        value_template: "{{ states.input_boolean.cottage_guest_mode.state == 'on' }}"
        friendly_name: 'Auto'
        device_class: safety
#### Workday
  - platform: workday
    country: SE
    name: workday
#### MQTT
  # - platform: mqtt
  #   name: ESP32 test status
  #   state_topic: upstairs_lolin32/binary_sensor/esp32_test_status/state

input_select:
  cottage_status:
      name: 'Cottage status'
      options:
       - Home
       - Away
       - Night
       - Standby
      initial: Standby
      icon: mdi:security

input_number:
  heater_delay:
    name: "Time to overrun"
    icon: mdi:timer
    initial: 30
    min: 0
    max: 60
    step: 5
    unit_of_measurement: min

input_boolean:
  workdays_only:
    name: Only active on workdays
    initial: True
  # lars_pickup:
  #   name: 'Lars lämna på förskolan'
  #   initial: 'on'
  #   icon: mdi:bus-school
  cottage_update:
    name: 'Auto'
    initial: 'on'
    icon: mdi:security
  cottage_guest_mode:
    name: 'Gästläge'
    initial: 'off'
    icon: mdi:security
  trigger_first_morning:
    name: 'Waiting for first morning motion'
    icon: mdi:kettle

input_datetime:
  heater_departuretime:
    name: "Departure time"
    has_date: False
    has_time: True
    initial: '07:00'

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave
