homeassistant:
  name: Slätberget
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Stockholm

  #Customize
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  #Packages
  packages: !include_dir_named packages

zone:
  name: 'Home'
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 136
  radius: 100

zone 2:
  name: 'FEV'
  latitude: !secret latitude_l_work
  longitude: !secret longitude_l_work
  radius: 700

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 192.168.100.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Enables the frontend
frontend:
#  javascript_version: latest

# New person mode
person:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: True

# Discover some devices automatically
#discovery:

# Activate cloud component
cloud:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

influxdb:
  host: 192.168.1.4
  port: 8086
  database: hass
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  exclude:
    entities:
      - sun.sun
      - sensor.time
      - sensor.last_boot
      - sensor.date
  include:
    domains:
      - sensor
      - light
      - switch
      - device_tracker
  tags:
    source: hass

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 50
  purge_interval: 5
  exclude:
    domains:
#      - automation
#      - script
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.time
      - sensor.last_boot
      - sensor.date
      - group.door_sensors
      - group.motion_sensors

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

vera:
  vera_controller_url: http://192.168.1.5:3480/
  exclude: [116]
  lights: [81, 62, 61, 60, 115, 136]

neato:
  username: !secret neato_username
  password: !secret neato_password

# Old nibe
#nibe:
#    client_id: !secret nibe_id
#    client_secret: !secret nibe_secret
#    redirect_uri: !secret nibe_url
#    writeaccess: false # set to true to support climate write (needs new tokens) and payment to Nibe
#    systems:
#        - system: '31372'
#          units:
#            - unit: 0
#              categories:

nibe:
    systems:
        - system: '31372'
          units:
            - unit: 0
              categories: True
              statuses: True
          climates: False
          water_heaters: False

ffmpeg:

camera:
  - platform: synology
    url: https://192.168.1.4:5001
    username: !secret synology_user
    password: !secret synology_pass
    timeout: 30
    verify_ssl: False

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Starta larmet!!'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Tysta larmet'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
      - name: Notification
        identifier: 'notis'
        actions:

owntracks:
  max_gps_accuracy: 300

device_tracker:
  - platform: unifi
    host: 192.168.1.2
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    ssid_filter:
      - 'RunevadHome'
      - 'RunevadGuest'
    monitored_conditions:
      - ip
      - radio
      - _is_guest_by_uap
      - _last_seen_by_uap
      - _uptime_by_uap
    consider_home: 300
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
#
  - platform: bluetooth_tracker

sun:

map:

tts:
  - platform: google
    language: 'sv'
    time_memory: 21600

system_health:

shell_command:
  restart_hass: 'curl http://127.0.0.1:8126/container/homeassistant/restart'

utility_meter:
  daily_energy:
    source: sensor.energy_month
    cycle: daily
  monthly_energy:
    source: sensor.energy_month
    cycle: monthly
  monthly_car_heater_energy:
    source: sensor.energy_car_heater
    cycle: monthly

automation: !include automations.yaml
group: !include_dir_merge_named group
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
