homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      allow_bypass_login: true
      trusted_users:
        192.168.1.0/24:
          - 9b40eeeaefb24820940f02bc9ddbad86
  #Customize
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  #Packages
  packages: !include_dir_named packages

default_config:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
#  ip_ban_enabled: True
#  login_attempts_threshold: 5

updater:
  include_used_components: true

conversation:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'sv'
    time_memory: 21600

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  purge_interval: 5
  exclude:
    domains:
      # - script
      - weather
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_utc
      - sensor.last_boot
      # - group.door_sensors
      # - group.door_units
      # - group.motion_sensors
      # - group.motion_units

logbook:
  # exclude:
  #   domains:
  #     - device_tracker

logger:
   default: info
   # logs:
   #   pydeconz: debug
   #   homeassistant.components.deconz: debug

influxdb:
  host: 192.168.1.4
  port: 8086
  database: hass
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - light
      - switch
      - device_tracker
  exclude:
    entities:
      - sun.sun
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_utc
      - sensor.last_boot
  tags:
    source: hass

zwave:
  usb_path: /dev/ttyACM1
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_key

# zha:
#   usb_path: /dev/ttyACM0
#   database_path: /config/zigbee.db
#
nibe:
  systems:
    - system: '31372'
      units:
        - unit: 0
          categories: True
          statuses: True
#      climates: False
      water_heaters: True
      sensors:
        - 40067 #avg outdoor temp
        - 40015 #brine in
        - 40016 #brine out
        - 40012 #return temp
        - 43439 #brine pump speed
        - 43437 #pump heat medium speed
        - 43009 #calculated flow temp
        - 40072 #Flow l/s
        - 40008 #heat medium flow
        - 40004 #outdoor temp
        - 40033 #indoor temp
        - 43005 #Degree minutes (DM)
        - 43136 #compressor hz
        - 43416 #number of compressor starts
        - 43420 #compressor operating time
        - 43424 #compressor operating time hot water
        - 44308 #heating with compressor (kWh)
        - 44300 #heating total (kWh)
        - 44298 #hot water (kWh)
        - 40083 #Amps L1
        - 40081 #Amps L2
        - 40079 #Amps L3
        - 10069 #electricity price

utility_meter:
  daily_energy:
    source: sensor.energy_meter_energy
    cycle: daily
  monthly_energy:
    source: sensor.energy_meter_energy
    cycle: monthly

camera:
  - platform: generic
    name: front
    still_image_url: !secret front_camera_still_url
    stream_source: !secret front_camera_stream_url
    username: !secret camera_username
    password: !secret camera_password
    authentication: digest
    verify_ssl: False
  # - platform: onvif
  #   name: carport
  #   host: !secret carport_camera_url
  #   port: !secret camera_port
  #   username: !secret camera_username
  #   password: !secret camera_password
  - platform: generic
    name: indoor
    still_image_url: !secret indoor_camera_still_url
    stream_source: !secret indoor_camera_stream_url
    username: !secret camera_username
    password: !secret camera_password
    authentication: digest
    verify_ssl: False

owntracks:
  max_gps_accuracy: 300

group: !include_dir_merge_named group

automation: !include automations.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

switch: !include switch.yaml

scene: !include scenes.yaml

light:
  - platform: switch
    name: window_lights_downstairs
    entity_id: switch.window_lights_downstairs
  - platform: switch
    name: window_lights_upstairs
    entity_id: switch.window_lights_upstairs
  - platform: switch
    name: hall_stairs_light
    entity_id: switch.hall_stairs_light
  - platform: switch
    name: laundry_window_light
    entity_id: switch.laundry_window_light
  - platform: switch
    name: living_room_window_light
    entity_id: switch.living_room_window_light

binary_sensor:
  - platform: template
    sensors:
      cottage_status_home:
        value_template: "{{ states.group.family.state == 'home' }}"
        friendly_name: 'Home'
        device_class: occupancy
      cottage_update:
        value_template: "{{ states.input_boolean.cottage_update.state == 'off' }}"
        friendly_name: 'Auto'
        device_class: safety
      cottage_guest_mode:
        value_template: "{{ states.input_boolean.cottage_guest_mode.state == 'on' }}"
        friendly_name: 'Auto'
        device_class: safety
#### Workday
  - platform: workday
    country: SE
    name: workday
#### MQTT
  # - platform: mqtt
  #   name: ESP32 test status
  #   state_topic: upstairs_lolin32/binary_sensor/esp32_test_status/state

input_select:
  cottage_status:
      name: 'Cottage status'
      options:
       - Home
       - Away
       - Night
       - Standby
      initial: Standby
      icon: mdi:security

input_number:
  heater_delay:
    name: "Time to overrun"
    icon: mdi:timer
    initial: 30
    min: 0
    max: 60
    step: 5
    unit_of_measurement: min

input_boolean:
  workdays_only:
    name: Only active on workdays
    initial: True
  # lars_pickup:
  #   name: 'Lars lämna på förskolan'
  #   initial: 'on'
  #   icon: mdi:bus-school
  cottage_update:
    name: 'Auto'
    initial: 'on'
    icon: mdi:security
  cottage_guest_mode:
    name: 'Gästläge'
    initial: 'off'
    icon: mdi:security
  trigger_first_morning:
    name: 'Waiting for first morning motion'
    icon: mdi:kettle

input_datetime:
  heater_departuretime:
    name: "Departure time"
    has_date: False
    has_time: True
    initial: '07:00'
  wake_up_workday:
    name: "Wake up time!"
    has_date: False
    has_time: True
    initial: '05:50'
