## Switches
##########################################

## Synology (custom component)
- platform: synologysurveillance
  url: https://192.168.1.4:5001
  username: !secret synology_user
  password: !secret synology_pass
  verify_ssl: false

## MQTT
- platform: mqtt
  name: Weather station restart switch
  state_topic: wemos_weather_station/switch/weather_station_restart_switch/state
  command_topic: wemos_weather_station/switch/weather_station_restart_switch/command
  icon: mdi:restart

## HA-Dockermon
- platform: rest
  resource: http://127.0.0.1:8126/container/homeassistant
  name: Hass
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/mariadb
  name: MariaDB
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/mosquitto
  name: MQTT
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/grafana
  name: Grafana
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/influxdb
  name: Influxdb
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
