#######################
## Security Groups
#######################

security:
  name: "Security"
  view: no
  icon: mdi:security
  entities:
    - group.door_sensors
    - group.motion_sensors
    - group.smoke_sensors

# motion_units:
#   name: "Rörelsesensorer on/off"
#   view: no
#   icon: mdi:security
#   control: hidden
#   entities:
#     - switch.motion_allrum_20
#     - switch.motion_hall_11
#
# door_units:
#   name: "Dörrsensorer on/off"
#   view: no
#   icon: mdi:security
#   control: hidden
#   entities:
#     - switch.door_altan_29
#     - switch.door_forrad_132
#     - switch.door_groventre_137
#     - switch.door_hall_35
#
# smoke_units:
#   name: "Brandvarnare on/off"
#   view: no
#   icon: mdi:fire
#   control: hidden
#   entities:
#     - switch.smokesensor_allrum_18
#     - switch.smokesensor_forrad_126
#     - switch.smokesensor_groventre_124
#     - switch.smokesensor_vardagsrum_133

door_sensors:
  name: "Dörrsensorer"
  view: no
  icon: mdi:glassdoor
  entities:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_02529123_1_6 #Altandörr
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_025184e5_1_6 #Förrådsdörr
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_02529083_1_6 #Groventre
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_32f43602_1_6 #Halldörr

motion_sensors:
  name: "Rörelsesensorer"
  view: no
  icon: mdi:run-fast
  entities:
    - binary_sensor.lumi_lumi_sensor_motion_aq2_fbc65302_1_1280 #Downstairs
    - binary_sensor.lumi_lumi_sensor_motion_aq2_262a7502_1_1280 #Upstairs

smoke_sensors:
  name: "Brandsensorer"
  view: no
  icon: mdi:fire
  entities:
    - binary_sensor.smoke_sensor_upstairs
    - binary_sensor.smoke_sensor_storage
    - binary_sensor.smoke_sensor_laundry
    - binary_sensor.smoke_sensor_kitchen
