#######################
## Security Groups
#######################

security:
  name: "Security"
  view: no
  icon: mdi:security
  entities:
    - group.door_sensors
    - group.motion_sensors
    - group.smoke_sensors

door_sensors:
  name: "Dörrsensorer"
  view: no
  icon: mdi:glassdoor
  entities:
    - binary_sensor.patio_door_sensor #Altandörr
    # - binary_sensor.storage_door_sensor #Förrådsdörr
    - binary_sensor.laundry_door_sensor #Groventre
    - binary_sensor.hall_door_sensor #Halldörr

motion_sensors:
  name: "Rörelsesensorer"
  view: no
  icon: mdi:run-fast
  entities:
    - binary_sensor.hall_motion_sensor #Hall
    - binary_sensor.family_room_motion_sensor #Allrum
    - binary_sensor.living_room_motion_sensor #Vardagsrum (IKEA)

smoke_sensors:
  name: "Brandsensorer"
  view: no
  icon: mdi:fire
  entities:
    - binary_sensor.family_room_smoke_detector
    - binary_sensor.storage_smoke_detector
    - binary_sensor.laundry_smoke_detector
    - binary_sensor.kitchen_smoke_detector
    - binary_sensor.ingrid_smoke_detector
    - binary_sensor.kerstin_smoke_detector
    - binary_sensor.master_bedroom_smoke_detector

storage_carport_sensors:
    - binary_sensor.storage_door_sensor #Förrådsdörr
