#Add HA Alarm Panel later for better support of delay etc. 

#################################################################
## Security System
##################################
- id: Alarm on from iOS notification
  alias: Sound the alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  action:
    - service: homeassistant.turn_on
      entity_id: script.sonos_alarm

- id: Alarm off from iOS notification
  alias: Turn alarm off from iOS
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
    - service: media_player.turn_off

## Sensor trip
#################################
- id: sensors_changed_when_nobody_home
  alias: 'Sensors tripped when nobody is home'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.cottage_update
        state: 'on'
      - condition: state
        entity_id: input_select.cottage_status
        state: 'Away'
  trigger:
    - platform: state
      entity_id:
        - group.smoke_sensors
        - group.motion_sensors
        - group.door_sensors
      from: 'off'
      to: 'on'
  action:
    - delay: '00:03:00'
    - condition: state
      entity_id: group.houshold
      state: 'away'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: notify.ios_lars_iphone
      data_template:
        title: "LARM!"
        message: "The {{ trigger.to_state.name }} was changed to {{ trigger.to_state.state }} while no one is home - {{ as_timestamp(now()) | timestamp_custom('%Y-%m-%d %H:%M:%S', true) }}"
        data:
          push:
            badge: 666
            category: "alarm"
    - service: homeassistant.turn_on
      entity_id: script.sonos_alarm

- id: door_open
  alias: 'Door open if night or away'
  initial_state: 'on'
  condition:
    - condition: state
      entity_id: group.door_sensors
      state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.cottage_status
      to: 'Night'
    - platform: state
      entity_id: input_select.cottage_status
      to: 'Away'
  action:
    - service: notify.ios_lars_iphone
      data_template:
        title: "Dörr öppen!"
        message: "{{ trigger.to_state.name }} är öppen!"
        data:
          push:
            badge: 555
            category: "alarm"


- id: storage_cold
  alias: "Kallt i förråd"
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.smoke_temp_forrad_127
      below: '12'
  action:
    - service: notify.ios_lars_iphone
      data:
        title: "Larm"
        message: "Det är under 12°C i förrådet!"
        data:
#          subtitle: "Test undertitel"
          push:
            badge: 500
            category: "alarm"
