#
neato:
  username: !secret neato_username
  password: !secret neato_password

######################

group:
  neato:
    name: "StädStina"
    view: yes
    icon: mdi:robot-vacuum-variant
    entities:
      - vacuum.stadstina
      - switch.stadstina_schedule
      - camera.stadstina_cleaning_map

######################
#Not tested completely

automation:
  - id: cleaning_robot_running
    alias: 'Shut down sensors when Neato is running'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.stadstina
        to: 'on'
    action:
      - service: homeassistant.turn_off
        data: 
          entity_id: group.motion_units

  - id: cleaning_robot_docked
    alias: 'Activate sensors when Neato is ready if Cottage is in Away mode'
    initial_state: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.cottage_update
          state: 'on'
        - condition: state
          entity_id: input_select.cottage_status
          state: 'Away'
    trigger:
      - platform: state
        entity_id: vacuum.stadstina
        to: 'off'
    action:
      - service: homeassistant.turn_on
        data: 
          entity_id: group.motion_units